### ISSUE TITLE
작업 분리: 링크 생성 / 엑셀 작업

### ISSUE THREAD

**Issue by ottlseo** [ottl-seo/ncloud-certification-rpa#24]
## Task
미리 링크를 만들어두고 저장해두면, 엑셀을 붙여넣었을 땐 바로바로 붙여넣기만 할 수 있게 작업 분리하기

## Reason to add this feature
링크 생성이 꼭 엑셀 작업이랑 순서대로 진행돼야 하는 일은 아닌데, 
자꾸 링크 생성(로그인) 단계에서 이런저런 오류가 발생해 필요할 때 못 쓰는 상황이 있다

## How
링크 생성은 인원수에 관계없이 100개 이상 만들어두고, 엑셀 작업은 필요할 때 그때그때 빠르게 작업할 수 있도록 변경할 예정

- - - 
## To do
- [x] 1. 모듈 분리 -> crawler / xlsx-handler 
- [x] 2. 100개씩 크롤링해서 새로운 엑셀 파일에 붙여넣기
- [ ] 3. 응시자 수 만큼 엑셀에서 읽기 → 삭제 → 붙여넣기 작업

- - - 
# 순서
#### `link_generator.py`
1. List.xlsx 파일에서 n 읽어오기
2. (n+2)행부터 링크 100개 쌓기

#### `sheet_handler.py`
3. 기존 파일에서 중복 제거해서 mail sheet 엑셀 파일 만들기
4. List.xlsx 파일에서 n 읽어와서 응시자 수(NUM_OF_PEOPLE)와 비교
    - `n < NUM_OF_PEOPLE` 인 경우→ Exception (link_generator 실행)
    - `n < NUM_OF_PEOPLE` 인 경우→ pass
    
5. List.xlsx 파일 `row=2`부터 읽어와서 mail sheet에 붙여넣기
6. List.xlsx 파일 `row=2`부터 `row=NUM_OF_PEOPLE+2`행까지 삭제하기

7. 중복 행 고려해서 PT 확인용 시트 새로 만들기

**Comment by ottlseo** [comment]
- [txt 파일 한줄씩 읽기](https://wikidocs.net/82#:~:text=txt%20%ED%8C%8C%EC%9D%BC%EC%9D%84%20%EC%97%B4%EC%96%B4%EB%B3%B4%EA%B2%A0%EC%8A%B5%EB%8B%88%EB%8B%A4.&text=%ED%8C%8C%EC%9D%BC%EC%9D%84%20%EC%B2%98%EC%9D%8C%EB%B6%80%ED%84%B0%20%EB%81%9D%EA%B9%8C%EC%A7%80,()%20%EC%9D%84%20%EC%82%AC%EC%9A%A9%ED%95%98%EC%8B%9C%EB%A9%B4%20%EB%90%A9%EB%8B%88%EB%8B%A4.)
- [엑셀 ROW 삭제](https://bebeya.tistory.com/entry/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%97%91%EC%85%80-%EC%8B%9C%ED%8A%B8-%EB%8B%A8%EC%9D%BC%EB%8B%A4%EC%A4%91-%ED%96%89-%EC%82%AD%EC%A0%9C-deleterows)

**Comment by ottlseo** [comment]
# 순서
#### `link_generator.py`
1. List.xlsx 파일에서 n 읽어오기
2. (n+2)행부터 링크 100개 쌓기

#### `sheet_handler.py`
3. 기존 파일에서 중복 제거해서 mail sheet 엑셀 파일 만들기
4. List.xlsx 파일에서 n 읽어와서 응시자 수(NUM_OF_PEOPLE)와 비교
    - `n < NUM_OF_PEOPLE` 인 경우→ Exception (link_generator 실행)
    - `n < NUM_OF_PEOPLE` 인 경우→ pass
    
5. List.xlsx 파일 `row=2`부터 읽어와서 mail sheet에 붙여넣기
6. List.xlsx 파일 `row=2`부터 `row=NUM_OF_PEOPLE+2`행까지 삭제하기

7. 중복 행 고려해서 PT 확인용 시트 새로 만들기
